apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nexacart-db-secret
  namespace: nexacart
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: nexacart-aws-secrets
    kind: ClusterSecretStore

  target:
    name: nexacart-db-secret
    creationPolicy: Owner

  data:
    - secretKey: POSTGRES_DB
      remoteRef:
        key: nexacart/database
        property: POSTGRES_DB

    - secretKey: POSTGRES_USER
      remoteRef:
        key: nexacart/database
        property: POSTGRES_USER

    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: nexacart/database
        property: POSTGRES_PASSWORD

    - secretKey: DB_NAME
      remoteRef:
        key: nexacart/database
        property: DB_NAME

    - secretKey: DB_USER
      remoteRef:
        key: nexacart/database
        property: DB_USER

    - secretKey: DB_PASSWORD
      remoteRef:
        key: nexacart/database
        property: DB_PASSWORD